apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment-test
  labels:
    app: postgres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name:  postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres

